# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mi < Formula
  desc "CLI tool for compose notes to Misskey"
  homepage "https://github.com/canoypa/mi"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/canoypa/mi/releases/download/v0.1.0/mi_0.1.0_darwin_arm64.tar.gz"
      sha256 "257605f270d535f00f7aa65fd79ce6d3e2d7e13731a1ee276991f3a33e1c2110"

      def install
        bin.install "mi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/mi/releases/download/v0.1.0/mi_0.1.0_darwin_amd64.tar.gz"
      sha256 "adce901d348a84d5a12ba4857467120adaa69bc75709a3273fb30dbd52e9c38c"

      def install
        bin.install "mi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canoypa/mi/releases/download/v0.1.0/mi_0.1.0_linux_arm64.tar.gz"
      sha256 "33054546e6233b9992af1f42e4902695cb7ca7f5417d7af6ddf5eaa925300b38"

      def install
        bin.install "mi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/mi/releases/download/v0.1.0/mi_0.1.0_linux_amd64.tar.gz"
      sha256 "414311871a9a0e6446d6ffbc98e8931e251eb32720beb20150885dd4b1835d33"

      def install
        bin.install "mi"
      end
    end
  end
end
