# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mi < Formula
  desc "CLI tool for compose notes to Misskey"
  homepage "https://github.com/canoypa/mi"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/canoypa/mi/releases/download/v0.1.1/mi_0.1.1_darwin_arm64.tar.gz"
      sha256 "809f7f48588645dfb11e501164b2df84d17f0045ab426546886cc5202b330659"

      def install
        bin.install "mi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/mi/releases/download/v0.1.1/mi_0.1.1_darwin_amd64.tar.gz"
      sha256 "2aa09bbdc023c22bf156d6cd09fab79c25011f61c24c34fe07717fdeedbb0b75"

      def install
        bin.install "mi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/canoypa/mi/releases/download/v0.1.1/mi_0.1.1_linux_arm64.tar.gz"
      sha256 "5dfb12a0d519efa11fe8897666540176cf9aced51f277d88b905f7d46daf0706"

      def install
        bin.install "mi"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/canoypa/mi/releases/download/v0.1.1/mi_0.1.1_linux_amd64.tar.gz"
      sha256 "d985c4eab3ddaebf80680b3f24908e1d87b95a5feadcd24f91caa94b40b98281"

      def install
        bin.install "mi"
      end
    end
  end
end
